[package]
name = "variant"
authors = ["Marcus Desai"]
version = "0.1.0"
edition = "2021"
autotests = false

[[test]]
name = "tests"
path = "tests/all_tests.rs"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[dependencies]
extract-impl = { path = "extract" }
