[package]
name = "extract-impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# todo: remove "extra-traits" feature from syn upon piblish.
syn = { version = "1.0", features = ["full", "extra-traits", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
